version: "3.9"
services:
  finance-server:
    build: .
    container_name: finance_server
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: finance
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
